[build]
  command = "rm -rf aruba-packing/bubble-frame && cp -R bubble-frame aruba-packing/bubble-frame"
  publish = "aruba-packing"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
